/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/**
 * Enum used to indicate true or false (also: success or failure, enabled or disabled, active or inactive).
 */
public class BOOL {
   public static final int BOOL_FALSE = 0; /* False. | */
   public static final int BOOL_TRUE = 1; /* True. | */
   public static final int BOOL_ENUM_END = 2; /*  | */
}